server:
  port: 8001

spring:
  application:
    name: service-cousumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true

